name: Mage Build Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "README_zh-CN.md"
      - "**.md"
      - "CONTRIBUTING.md"
      - ".github/**"
  pull_request:
    branches: 
      - main
    paths-ignore:
      - "README.md"
      - "README_zh-CN.md"
      - "**.md"
      - "CONTRIBUTING.md"
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    name: Execute Mage On Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: init
        run: sudo bash bootstrap.sh
        timeout-minutes: 20

      - name: Build, Start, Check Services and Print Logs for Linux
        run: |
          sudo mage
          sudo mage start
          sudo mage check

      - name: Restart Services and Print Logs
        run: |
          sudo mage stop
          sudo mage start
          sudo mage check
